# Generated by Django 3.2 on 2023-06-06 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_titleimport'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TitleImport',
        ),
    ]
