# Generated by Django 3.2 on 2023-06-11 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_auto_20230611_0948'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
